### ISSUE TITLE
`oauth2: cannot fetch token` error preventing get method to succeed

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-gcscli#20]
```
Error: Action Failed get_task: Task zzz result: Applying: Applying job consul_agent: Applying package adapter for job consul_agent: Fetching package blob: Getting blob from inner blobstore: Getting blob from inner blobstore: Shelling out to bosh-blobstore-gcs cli: Running command: 'bosh-blobstore-gcs -c /var/vcap/bosh/etc/blobstore-gcs.json get xxx yyy', stdout: '', stderr: '2018/03/02 18:42:14 Get https://www.googleapis.com/storage/v1/b/pcflabs-boshblobs?alt=json&projection=full: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 74.125.141.84:443: i/o timeout
': exit status 1
```

added this issue for now for tracking. i believe agent currently does some form of retrying, though i dont see in the error message.

similar issue in cpi: https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/issues/203

**Comment by dpb587-pivotal** [comment]
I don't believe bosh-agent does retries... https://github.com/cloudfoundry/bosh-utils/blob/01cfe283d17a7b5aa18f03c1a1d8eb78cf25e249/blobstore/external_blobstore.go#L51

I don't believe the gcscli retries gets either... https://github.com/cloudfoundry/bosh-gcscli/blob/2aef468b5b8561560918014b4fbce7549de2283d/client/client.go#L93

**Comment by 2tim** [comment]
Any update on this? I seem to be having the same issue after moving from using S3 compatible to GCS.

**Comment by evandbrown** [comment]
@josephlewis42 could you take a look at this when you have a moment, please?

**Comment by josephlewis42** [comment]
Looking into this:

The HTTP/GRPC stuff that deals with  should be fine because the google-cloud-go library is supposed to handle retries as long as the context.Context is valid and it includes code for exponential backoff. See: https://cloud.google.com/storage/docs/exponential-backoff for more info.

There is a difference between this and https://github.com/cloudfoundry/bosh-google-cpi-release/issues/203 because that application is using the deprecated Google generated API: https://godoc.org/google.golang.org/api/storage/v1 whereas this one is using the current: https://godoc.org/cloud.google.com/go/storage, however behind the scenes it looks like they both boil down to using the same code to construct new clients. 

For the modern lib it goes through here: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/storage.go#L88 to get to here: https://github.com/googleapis/google-api-go-client/blob/master/transport/http/dial.go#L34:6

The problem looks like that code will always call [this function](https://github.com/googleapis/google-api-go-client/blob/master/transport/http/dial.go#L63) which sets up the credential fetching OAUTH with go's default HTTP transport, meaning we have to modify the default to include a retrying roundtripper and/or a longer timeotu (unless I'm missing something).

I'd recommend basing the default roundtripper off [this code](https://github.com/googleapis/google-api-go-client/blob/master/gensupport/retry.go) so we can retry indefinitely, or to the end of a context based on wall-clock time that a user would find acceptable rather than an arbitrary number of times. Without a full stack-trace it's difficult to determine if a dial timeout error is a net error that has the retryable flag set, but based on some of the code I found it looks like it might be so we could try using that code out of the box.

**Comment by josephlewis42** [comment]
@evandbrown, I added a proposed fix, it's based on what I saw when digging down the API client rabbit-hole. Not super clean, and I'm looking for ideas about how to test it correctly without dedicating a significant chunk of work towards this single issue.

**Comment by christoph-puppe** [comment]
Is this related then?

Do I have to wait for a fix or can I do anything to prevent it from running into the timeout?

Task 34 | 10:31:59 | Update stemcell: Uploading stemcell bosh-google-kvm-ubuntu-xenial-go_agent/97.28 to the cloud (cpi: 437bd5f14b2c13913774) (00:00:30)

                   L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating stemcell: Creating Google Image from URL: Failed to create Google Image: Post https://www.googleapis.com/compute/v1/projects/pcf-test-1/global/images?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 74.125.131.84:443: i/o timeout' in 'create_stemcell' CPI method (CPI request ID: 'cpi-729640')

Task 34 | 10:32:29 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating stemcell: Creating Google Image from URL: Failed to create Google Image: Post https://www.googleapis.com/compute/v1/projects/pcf-test-1/global/images?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 74.125.131.84:443: i/o timeout' in 'create_stemcell' CPI method (CPI request ID: 'cpi-729640')
